package com.shixianghui.base.dao;

public class XtDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dict.item_id
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dict.item_code
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dict.item_name
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dict.status
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dict.item_id
     *
     * @return the value of xt_dict.item_id
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dict.item_id
     *
     * @param itemId the value for xt_dict.item_id
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dict.item_code
     *
     * @return the value of xt_dict.item_code
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dict.item_code
     *
     * @param itemCode the value for xt_dict.item_code
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dict.item_name
     *
     * @return the value of xt_dict.item_name
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dict.item_name
     *
     * @param itemName the value for xt_dict.item_name
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dict.status
     *
     * @return the value of xt_dict.status
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dict.status
     *
     * @param status the value for xt_dict.status
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}