package com.shixianghui.base.dao;

import java.util.Date;

public class XtGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.goods_id
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.goods_name
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.goods_type
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private String goodsType;
    private String goodsTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.img_url
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.market_price
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private Double marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.trade_price
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private Double tradePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.unit
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private String unit;
    private String unitName;

    public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.inventory
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private Integer inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.status
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.creater_id
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private String createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_goods.create_time
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    private Date createTime;
    private String createTimeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.goods_id
     *
     * @return the value of xt_goods.goods_id
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.goods_id
     *
     * @param goodsId the value for xt_goods.goods_id
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.goods_name
     *
     * @return the value of xt_goods.goods_name
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.goods_name
     *
     * @param goodsName the value for xt_goods.goods_name
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.goods_type
     *
     * @return the value of xt_goods.goods_type
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.goods_type
     *
     * @param goodsType the value for xt_goods.goods_type
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.img_url
     *
     * @return the value of xt_goods.img_url
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.img_url
     *
     * @param imgUrl the value for xt_goods.img_url
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.market_price
     *
     * @return the value of xt_goods.market_price
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.market_price
     *
     * @param marketPrice the value for xt_goods.market_price
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.trade_price
     *
     * @return the value of xt_goods.trade_price
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public Double getTradePrice() {
        return tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.trade_price
     *
     * @param tradePrice the value for xt_goods.trade_price
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setTradePrice(Double tradePrice) {
        this.tradePrice = tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.unit
     *
     * @return the value of xt_goods.unit
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.unit
     *
     * @param unit the value for xt_goods.unit
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.inventory
     *
     * @return the value of xt_goods.inventory
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.inventory
     *
     * @param inventory the value for xt_goods.inventory
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.status
     *
     * @return the value of xt_goods.status
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.status
     *
     * @param status the value for xt_goods.status
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.creater_id
     *
     * @return the value of xt_goods.creater_id
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.creater_id
     *
     * @param createrId the value for xt_goods.creater_id
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_goods.create_time
     *
     * @return the value of xt_goods.create_time
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_goods.create_time
     *
     * @param createTime the value for xt_goods.create_time
     *
     * @mbggenerated Wed Oct 25 23:17:44 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getGoodsTypeName() {
		return goodsTypeName;
	}

	public void setGoodsTypeName(String goodsTypeName) {
		this.goodsTypeName = goodsTypeName;
	}

	public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}
}