package com.shixianghui.base.dao;

import java.util.List;

public class XtMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_menu.id
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_menu.name
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_menu.url
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_menu.parent_id
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_menu.authority
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    private String authority;
    
    private List<XtMenu> menuDtls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_menu.id
     *
     * @return the value of xt_menu.id
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_menu.id
     *
     * @param id the value for xt_menu.id
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_menu.name
     *
     * @return the value of xt_menu.name
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_menu.name
     *
     * @param name the value for xt_menu.name
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_menu.url
     *
     * @return the value of xt_menu.url
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_menu.url
     *
     * @param url the value for xt_menu.url
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_menu.parent_id
     *
     * @return the value of xt_menu.parent_id
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_menu.parent_id
     *
     * @param parentId the value for xt_menu.parent_id
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_menu.authority
     *
     * @return the value of xt_menu.authority
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_menu.authority
     *
     * @param authority the value for xt_menu.authority
     *
     * @mbggenerated Mon Dec 11 14:52:38 CST 2017
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

	public List<XtMenu> getMenuDtls() {
		return menuDtls;
	}

	public void setMenuDtls(List<XtMenu> menuDtls) {
		this.menuDtls = menuDtls;
	}
}