package com.shixianghui.base.dao;

import java.util.Date;

public class XtUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.user_id
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.user_name
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.pass_word
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.name
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.gender
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.birth_date
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.user_type
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.higher_uid
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String higherUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.create_uid
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private String createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.create_time
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private Date createTime;
    private String createTimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_user.status
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.user_id
     *
     * @return the value of xt_user.user_id
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.user_id
     *
     * @param userId the value for xt_user.user_id
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.user_name
     *
     * @return the value of xt_user.user_name
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.user_name
     *
     * @param userName the value for xt_user.user_name
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.pass_word
     *
     * @return the value of xt_user.pass_word
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.pass_word
     *
     * @param passWord the value for xt_user.pass_word
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.name
     *
     * @return the value of xt_user.name
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.name
     *
     * @param name the value for xt_user.name
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.gender
     *
     * @return the value of xt_user.gender
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.gender
     *
     * @param gender the value for xt_user.gender
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.birth_date
     *
     * @return the value of xt_user.birth_date
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.birth_date
     *
     * @param birthDate the value for xt_user.birth_date
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.user_type
     *
     * @return the value of xt_user.user_type
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.user_type
     *
     * @param userType the value for xt_user.user_type
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.higher_uid
     *
     * @return the value of xt_user.higher_uid
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getHigherUid() {
        return higherUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.higher_uid
     *
     * @param higherUid the value for xt_user.higher_uid
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setHigherUid(String higherUid) {
        this.higherUid = higherUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.create_uid
     *
     * @return the value of xt_user.create_uid
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.create_uid
     *
     * @param createUid the value for xt_user.create_uid
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.create_time
     *
     * @return the value of xt_user.create_time
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.create_time
     *
     * @param createTime the value for xt_user.create_time
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_user.status
     *
     * @return the value of xt_user.status
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_user.status
     *
     * @param status the value for xt_user.status
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}
}