package com.shixianghui.base.mapper;

import com.shixianghui.base.dao.XtDict;
import com.shixianghui.base.dao.XtDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XtDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int countByExample(XtDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int deleteByExample(XtDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int insert(XtDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int insertSelective(XtDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    List<XtDict> selectByExample(XtDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    XtDict selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") XtDict record, @Param("example") XtDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int updateByExample(@Param("record") XtDict record, @Param("example") XtDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(XtDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dict
     *
     * @mbggenerated Sun Oct 22 18:23:55 GMT+08:00 2017
     */
    int updateByPrimaryKey(XtDict record);
}