package com.shixianghui.base.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.shixianghui.base.dao.XtUser;
import com.shixianghui.base.dao.XtUserExample;

public interface XtUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int countByExample(XtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int deleteByExample(XtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int insert(XtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int insertSelective(XtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    List<XtUser> selectByExample(XtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    XtUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") XtUser record, @Param("example") XtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int updateByExample(@Param("record") XtUser record, @Param("example") XtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(XtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_user
     *
     * @mbggenerated Wed Nov 08 21:05:03 GMT+08:00 2017
     */
    int updateByPrimaryKey(XtUser record);

	List<XtUser> getUserLower(Map<String, String> map);

	List<XtUser> getPageByName(Map<String, Object> map);
}