package com.shixianghui.base.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.shixianghui.base.dao.YwSaleRecord;
import com.shixianghui.base.dao.YwSaleRecordExample;

public interface YwSaleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int countByExample(YwSaleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int deleteByExample(YwSaleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String saleRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int insert(YwSaleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int insertSelective(YwSaleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    List<YwSaleRecord> selectByExample(YwSaleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    YwSaleRecord selectByPrimaryKey(String saleRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") YwSaleRecord record, @Param("example") YwSaleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int updateByExample(@Param("record") YwSaleRecord record, @Param("example") YwSaleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(YwSaleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_sale_record
     *
     * @mbggenerated Sun Oct 29 13:36:00 GMT+08:00 2017
     */
    int updateByPrimaryKey(YwSaleRecord record);
    
    List<YwSaleRecord> getSaleRecords(Map<String, Object> map);

	Integer getSaleTotal(Map<String, Object> map);
}